In [1]:
import numpy as np

In [8]:
A=np.array([[1,4],[-1,3],[2,-9]])
cero=np.zeros((3,2))
print(r)

[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]


In [9]:
r=A+cero
print(r)

[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]


In [10]:
A=np.array([[3,0],[-1,5]])
B=np.array([[4,-2,1],[0,2,3]])
r=A@B
print(r)

[[12 -6  3]
 [-4 12 14]]


In [2]:
restaurantes = np.array([[30,15,4],[25,18,8]])
tiendas = np.array([[1.2,2.2,4.5],[1.3,2.1,4.6]])
print(tiendas.T)
costoPorTienda = restaurantes@tiendas.T
print(costoPorTienda)
print("Tienda 1", (costoPorTienda[0,0]+costoPorTienda[1,0]))
print("Tienda 2", (costoPorTienda[0,1]+costoPorTienda[1,1]))

[[1.2 1.3]
 [2.2 2.1]
 [4.5 4.6]]
[[ 87.   88.9]
 [105.6 107.1]]
Tienda 1 192.6
Tienda 2 196.0


In [20]:
productos_Almacen_1 = np.array([200,150,100])
productos_ALmacen_2 = np.array([75,100,125])
costoTren = np.array([[1.75,1.50,1.00]])
costoCamion = np.array([[1.50,1.00,2.00]])
camion = productos_Almacen_1@costoCamion.T + productos_ALmacen_2@costoCamion.T
tren = productos_Almacen_1@costoTren.T + productos_ALmacen_2@costoTren.T
print('Camion: ', camion)
print('Tren: ', tren)

Camion:  [1112.5]
Tren:  [1081.25]


In [26]:
#Primer Sitema de Ecuaciones:
A = np.array([[3, 2], [6, 4]])
B = np.array([6, -9])

adjunta = np.array([[A[1, 1], -A[0, 1]], [-A[1, 0], A[0, 0]]])
determinante = A[0, 0] * A[1, 1] - A[0, 1] * A[1, 0]
inversa = adjunta / determinante

solucion = inversa@B.T

x = solucion[0]
y = solucion[1]

print("Prmer Sistema")
print("x =", x)
print("y =", y)



Solución:
x = inf
y = -inf


C:\Users\stepp\AppData\Local\Temp\ipykernel_12988\1892549090.py:8: RuntimeWarning: divide by zero encountered in divide
  inversa = adjunta / determinante


In [28]:
#Segundo Sitema de Ecuaciones:
A = np.array([[1, 1], [1, -4]])
B = np.array([3, 1])

adjunta = np.array([[-4, -1], [-1, 1]])
determinante = 1 * (-4) - 1 * 1
inversa = adjunta / determinante

solucion = inversa@B.T

x = solucion[0]
y = solucion[1]

print("Segundo Sistema")
print("x =", x)
print("y =", y)


Segundo Sistema
x = 2.6000000000000005
y = 0.4000000000000001


In [29]:
#Tercer Sitema de Ecuaciones:
A = np.array([[2, -1, 2], [2, 3, -1], [1, 2, 2]])
B = np.array([3, 0, -12])

adjunta = np.array([[7, 6, -5], [-8, 8, -2], [-3, -4, 4]])
determinante = 2 * (3 * 4 - (-1) * 2) - (-1) * (2 * 4 - (-1) * 1) + 2 * (2 * (-4) - 3 * 1)
inversa = adjunta / determinante

solucion = inversa@B.T

x = solucion[0]
y = solucion[1]
z = solucion[2]

print("Tercer Sistema")
print("x =", x)
print("y =", y)
print("z =", z)


Tercer Sistema
x = 5.4
y = 0.0
z = -3.8000000000000003
